### ISSUE TITLE
Swift 4 compatibility

### ISSUE THREAD

**Issue by fhelg** [jverdi/Gramophone#2]
Hi there,

Thanks a lot for your useful library. Is there any plan to support Swift 4 any time soon ?

Cheers

**Comment by jverdi** [comment]
Hi @fhelg 

Thanks for the push. Want to give the `feature/swift-4` branch I just published a try?

PR: https://github.com/jverdi/Gramophone/pull/3

**Comment by fhelg** [comment]
Will sure have a look, thanks a lot for the reactivity!

**Comment by fhelg** [comment]
I didn't try the branch on my project yet (as I am migrating to Swift4 now), but I made the exact same changes yesterday as the one in your commit 52787e572e8f49d97f0849cf1c4f190b3f1dbdb4 
 to have my project compile against Swift 3.2.

**Comment by jverdi** [comment]
OK, PR is merged, and Swift 4 is now supported in the 1.1 release. Please re-open if you have any issues.
